(()=>{
'use strict';
const DEG=Math.PI/180,TAU=Math.PI*2;
let canvas,ctx,galaxy,galaxyCtx,raf=0,w=0,h=0,dpr=1,started=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
function vecFromLonLat(lon,lat){const p=lat*DEG,l=lon*DEG,c=Math.cos(p);return[c*Math.cos(l),c*Math.sin(l),Math.sin(p)]}
function cameraBasis(){const c=map.getCenter(),p=c.lat*DEG,l=c.lng*DEG,cp=Math.cos(p),sp=Math.sin(p),cl=Math.cos(l),sl=Math.sin(l);return{forward:[cp*cl,cp*sl,sp],east:[-sl,cl,0],north:[-sp*cl,-sp*sl,cp]}}
function astronomyEnabled(){try{return dayNightEnabled!==false}catch(e){return true}}
function addStyle(){const s=document.createElement('style');s.textContent='#sunVisual{display:none!important}#astronomyScene{position:fixed;inset:0;z-index:10;pointer-events:none;width:100%;height:100%;contain:strict}';document.head.appendChild(s)}
function ensureCanvas(){if(canvas)return;canvas=document.createElement('canvas');canvas.id='astronomyScene';canvas.setAttribute('aria-hidden','true');document.body.appendChild(canvas);ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});galaxy=document.createElement('canvas');galaxyCtx=galaxy.getContext('2d',{alpha:true});resize()}
function seeded(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function buildGalaxy(){if(!galaxyCtx)return;galaxy.width=Math.max(1,Math.round(w*dpr));galaxy.height=Math.max(1,Math.round(h*dpr));const g=galaxyCtx;g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);const veils=[[.18,.22,.95,'rgba(120,92,255,.10)'],[.82,.38,.72,'rgba(80,157,255,.07)'],[.50,.78,.86,'rgba(197,101,255,.055)']];for(const [x,y,r,col] of veils){const gr=g.createRadialGradient(w*x,h*y,0,w*x,h*y,Math.max(w,h)*r);gr.addColorStop(0,col);gr.addColorStop(.55,'rgba(80,100,220,.018)');gr.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=gr;g.fillRect(0,0,w,h)}const rnd=seeded(0x574f524c),count=clamp(Math.round(w*h/2200),90,230);for(let i=0;i<count;i++){const x=rnd()*w,y=rnd()*h,r=rnd()<.08?.8+rnd()*1.15:.25+rnd()*.65,a=.16+rnd()*.54;g.beginPath();g.arc(x,y,r,0,TAU);g.fillStyle=`rgba(${210+Math.floor(rnd()*45)},${220+Math.floor(rnd()*35)},255,${a})`;g.fill()}for(let i=0;i<12;i++){const x=rnd()*w,y=rnd()*h,r=1+rnd()*1.25;const gr=g.createRadialGradient(x,y,0,x,y,r*4);gr.addColorStop(0,'rgba(255,255,255,.75)');gr.addColorStop(.18,'rgba(190,205,255,.36)');gr.addColorStop(1,'rgba(120,100,255,0)');g.fillStyle=gr;g.fillRect(x-r*4,y-r*4,r*8,r*8)}}
function resize(){ensureCanvas();const r=map.getContainer().getBoundingClientRect();w=Math.max(1,r.width);h=Math.max(1,r.height);dpr=Math.min(window.devicePixelRatio||1,1.5);const pw=Math.round(w*dpr),ph=Math.round(h*dpr);if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);buildGalaxy()}schedule()}
function earthGeometry(){const center=map.getCenter(),pc=map.project(center),cx=pc.x,cy=pc.y;let radius=0;try{let lon=center.lng+90;while(lon>180)lon-=360;while(lon<-180)lon+=360;const limb=map.project([lon,0]);radius=Math.hypot(limb.x-cx,limb.y-cy)}catch(e){}if(!Number.isFinite(radius)||radius<18||radius>Math.max(w,h)*4)radius=Math.min(w,h)*.335*Math.pow(2,map.getZoom()-1.65);return{cx,cy,r:clamp(radius,24,Math.max(w,h)*4)}}
function sunState(){const s=solarSubpoint(new Date()),sv=vecFromLonLat(s.lon,s.lat),b=cameraBasis(),g=earthGeometry(),orbit=g.r*1.72,x=g.cx+dot(sv,b.east)*orbit,y=g.cy-dot(sv,b.north)*orbit,depth=dot(sv,b.forward),sunR=clamp(g.r*.19,21,48);return{...g,x,y,depth,sunR}}
function drawSun(x,y,r){ctx.save();let halo=ctx.createRadialGradient(x,y,r*.5,x,y,r*2.75);halo.addColorStop(0,'rgba(255,220,104,.26)');halo.addColorStop(.38,'rgba(255,175,54,.12)');halo.addColorStop(1,'rgba(255,128,32,0)');ctx.fillStyle=halo;ctx.beginPath();ctx.arc(x,y,r*2.75,0,TAU);ctx.fill();let core=ctx.createRadialGradient(x-r*.28,y-r*.30,r*.05,x,y,r);core.addColorStop(0,'#fffef1');core.addColorStop(.18,'#fff6b0');core.addColorStop(.58,'#ffd65b');core.addColorStop(.84,'#f6aa2f');core.addColorStop(1,'#df7919');ctx.fillStyle=core;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,238,168,.76)';ctx.lineWidth=Math.max(1,r*.025);ctx.stroke();ctx.restore()}
function eraseEarth(g){ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(g.cx,g.cy,g.r*1.008,0,TAU);ctx.fill();ctx.restore()}
function render(){raf=0;if(!canvas||!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!astronomyEnabled()){canvas.style.opacity='0';return}canvas.style.opacity='1';if(galaxy)ctx.drawImage(galaxy,0,0,galaxy.width,galaxy.height,0,0,w,h);const s=sunState();if(s.depth<0)drawSun(s.x,s.y,s.sunR);eraseEarth(s);if(s.depth>=0)drawSun(s.x,s.y,s.sunR)}
function schedule(){if(!raf)raf=requestAnimationFrame(render)}
function tuneMap(){try{map.setFog({color:'rgb(1,4,9)','high-color':'rgb(8,13,25)','horizon-blend':.04,'space-color':'rgb(0,1,6)','star-intensity':.08})}catch(e){}try{if(map.getLayer('night-side-fill'))map.setPaintProperty('night-side-fill','fill-opacity',.34);if(map.getLayer('twilight-18-fill'))map.setPaintProperty('twilight-18-fill','fill-opacity',.11);if(map.getLayer('twilight-12-fill'))map.setPaintProperty('twilight-12-fill','fill-opacity',.085);if(map.getLayer('twilight-6-fill'))map.setPaintProperty('twilight-6-fill','fill-opacity',.065);if(map.getLayer('terminator-line')){map.setPaintProperty('terminator-line','line-opacity',.18);map.setPaintProperty('terminator-line','line-width',.8)}}catch(e){}}
function accelerateRealtime(){try{clearInterval(solarTimer);solarTimer=setInterval(()=>{if(astronomyEnabled())syncDayNight();if(current)updateNowPlayingMarker(current);schedule()},15000)}catch(e){setInterval(schedule,15000)}}
function start(){if(started)return;started=true;addStyle();ensureCanvas();try{map.off('move',updateSunVisual);map.off('resize',updateSunVisual);updateSunVisual=schedule}catch(e){}map.on('move',schedule);map.on('zoom',schedule);map.on('resize',resize);map.on('moveend',schedule);const ready=()=>{resize();tuneMap();accelerateRealtime();try{syncDayNight()}catch(e){}schedule()};if(map.loaded())ready();else map.once('load',ready);window.addEventListener('orientationchange',()=>setTimeout(resize,120),{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});setInterval(schedule,5000)}
try{start()}catch(e){console.warn('Worldio astronomy v2 fallback',e)}
})();