import{MAPLIBRE_JS}from'./config.js';
let map=null,ready=false,stationList=[],eventsBound=false;
const loadScript=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;s.defer=true;document.head.appendChild(s)});
export async function ensureMapLibre(){if(window.maplibregl)return;let last;for(const src of MAPLIBRE_JS){try{await loadScript(src);if(window.maplibregl)return}catch(e){last=e}}throw last||Error('MapLibre unavailable')}
const style={version:8,sources:{},layers:[{id:'bg',type:'background',paint:{'background-color':'#06110d'}}]};
export async function initMap({onStation,onReady,onError}){try{await ensureMapLibre();map=new maplibregl.Map({container:'map',style,center:[12,25],zoom:1.55,attributionControl:true,dragRotate:false,touchPitch:false,minZoom:.6,maxZoom:10,fadeDuration:0});const timer=setTimeout(()=>{if(!ready)onError?.(Error('Map boot timeout'))},5000);map.on('load',()=>{clearTimeout(timer);ready=true;try{map.setProjection({type:'globe'});map.setFog({color:'rgb(2,7,6)','high-color':'rgb(8,25,20)','horizon-blend':.08,'space-color':'rgb(0,2,2)','star-intensity':.2})}catch{};onReady?.();queueMicrotask(addBaseMap)});map.on('error',e=>console.warn('Worldio map',e?.error||e));bindInteractions(onStation);return map}catch(e){onError?.(e);throw e}}
function addBaseMap(){if(!ready||map.getSource('osm'))return;try{map.addSource('osm',{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:7,attribution:'© OpenStreetMap contributors'});map.addLayer({id:'earth',type:'raster',source:'osm',paint:{'raster-opacity':.58,'raster-saturation':-.8,'raster-contrast':.18,'raster-brightness-max':.46}})}catch(e){console.warn('basemap',e)}}
function fc(list){return{type:'FeatureCollection',features:list.map(s=>({type:'Feature',geometry:{type:'Point',coordinates:[+s.geo_long,+s.geo_lat]},properties:{id:s.stationuuid}}))}}
export function setStations(list){stationList=list;if(!ready||!list.length)return;const data=fc(list);if(map.getSource('stations')){map.getSource('stations').setData(data);return}map.addSource('stations',{type:'geojson',data,cluster:true,clusterMaxZoom:7,clusterRadius:40});map.addLayer({id:'clusters',type:'circle',source:'stations',filter:['has','point_count'],paint:{'circle-color':'rgba(120,255,181,.28)','circle-radius':['step',['get','point_count'],11,20,15,60,20],'circle-stroke-width':1,'circle-stroke-color':'rgba(120,255,181,.8)'}});map.addLayer({id:'cluster-count',type:'symbol',source:'stations',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':10},paint:{'text-color':'#e5fff1'}});map.addLayer({id:'station-glow',type:'circle',source:'stations',filter:['!',['has','point_count']],paint:{'circle-color':'rgba(120,255,181,.18)','circle-radius':['interpolate',['linear'],['zoom'],1,5,6,10],'circle-blur':.75}});map.addLayer({id:'station-points',type:'circle',source:'stations',filter:['!',['has','point_count']],paint:{'circle-color':'#78ffb5','circle-radius':['interpolate',['linear'],['zoom'],1,1.8,6,4.2]}})}
function bindInteractions(onStation){if(eventsBound)return;eventsBound=true;document.addEventListener('worldio-map-ready',()=>{});const bind=()=>{if(!map||!ready)return;map.on('click','clusters',async e=>{const f=e.features?.[0];if(!f)return;const z=await map.getSource('stations').getClusterExpansionZoom(f.properties.cluster_id);map.easeTo({center:f.geometry.coordinates,zoom:Math.min(z,8),duration:500})});map.on('click','station-points',e=>{const id=e.features?.[0]?.properties?.id;const s=stationList.find(x=>x.stationuuid===id);if(s)onStation?.(s)});};const i=setInterval(()=>{if(ready&&map.getLayer('station-points')){clearInterval(i);bind()}},200);setTimeout(()=>clearInterval(i),15000)}
export function focusStation(s){if(!map||!ready)return;map.easeTo({center:[+s.geo_long,+s.geo_lat],zoom:Math.max(map.getZoom(),4.2),duration:750})}
export function getCenter(){return map?.getCenter?.()||{lng:0,lat:0}}
export function isReady(){return ready}
